# Generated by Django 6.0 on 2025-12-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='encodingjob',
            new_name='encoder_enc_status_ec40a7_idx',
            old_name='encoder_encoding_status_idx',
        ),
        migrations.RenameIndex(
            model_name='encodingjob',
            new_name='encoder_enc_video_i_4a4ed7_idx',
            old_name='encoder_encoding_video_id_idx',
        ),
        migrations.RenameIndex(
            model_name='encodingjob',
            new_name='encoder_enc_created_aedb05_idx',
            old_name='encoder_encoding_created_at_idx',
        ),
    ]
